### ISSUE TITLE
Can't import into Archimate

### ISSUE THREAD

**Issue by rmbaxter67** [scwcsu/snsde-archi-model#5]
I've cloned the repo but can't get a handle on anything for Archimate to open (either v5.0.1 or v5.2.0). It doesn't like any of the XML files, nor can I make the collaboration plugin read anything. Any assistance?

Background: I'm Rob Baxter, Tech Lead at DARE UK. I've been using Archimate (drawn "by hand" via diagrams.net/draw.io) to model TRE federation on the back of SATRE, other DARE UK drivers and v1.0 (Apr '23) of our original architecture blueprint. I'm really keen to see where you are with SDE modelling and how I should accomodate in my views.

**Comment by elementechemlyn** [comment]
Hi Rob.
Have you tried using the collaboration plugin to load the repo directly from github (rather than cloning it first)? 

Collaboration->Import Model to Workspace. You can then specify the same url you would use to clone. 

It *should* work with either http or ssh links but I've had more success with ssh: git@github.com:scwcsu/snsde-archi-model.git

**Comment by elementechemlyn** [comment]
Perhaps it added it to the collab workspace but didn't open it? Can you see the collab workspace - I think by default it opens to the right of the screen. Use Collaboration->Toggle Collaboration Workspace if it's not there. 

Is the model listed in that view? Right click and choose Open Model if it is.

**Comment by rmbaxter67** [comment]
Ah! Bingo! There it is (actually, I have three copies, one for each attemp :-) ). You know, I thought I'd tried that but clearly not. Thanks for your help! I'll close the issue.
